#pragma once

#include <stdint.h>

#if defined(__AVR__)
#include <avr/pgmspace.h>
#elif !defined(PROGMEM)
#define PROGMEM
#endif

// Generated by tools/convert_assets.py from assets/char*.PNG.
// Player walk sprites on a 9x7 canvas.
// Column-major: one byte per column, bit index = row.

const uint8_t playerFrames[][9] PROGMEM = {
    {0x00, 0x20, 0x18, 0x3d, 0x56, 0x3c, 0x18, 0x20, 0x00},
    {0x20, 0x20, 0x10, 0x38, 0x6e, 0x38, 0x10, 0x20, 0x20},
    {0x00, 0x20, 0x18, 0x3c, 0x56, 0x3d, 0x18, 0x20, 0x00},
};
static_assert(sizeof(playerFrames) == 27, "Unexpected player sprite frames");