#!/usr/bin/env python3
"""Convert RGBA menu PNGs to raw Arduboy drawBitmap headers."""

import argparse
from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
NAMES = (
    "intro",
    "mainmenu_play", "mainmenu_about", "mainmenu_sound", "mainmenu_exit",
    "soundmenu_on", "soundmenu_off", "soundmenu_exit",
)
WIDTH, HEIGHT, SCALE = 128, 64, 8
SOURCE_SIZE = (WIDTH * SCALE, HEIGHT * SCALE)


def parse_source(path):
    """Read and validate an exact 8x RGBA alpha-mask export."""
    try:
        with Image.open(path) as image:
            image.load()
            if image.format != "PNG":
                raise ValueError(f"{path}: expected PNG input")
            if image.mode != "RGBA":
                raise ValueError(f"{path}: expected RGBA, got {image.mode}")
            if image.size != SOURCE_SIZE:
                raise ValueError(
                    f"{path}: expected {SOURCE_SIZE[0]}x{SOURCE_SIZE[1]}, "
                    f"got {image.width}x{image.height}"
                )
            red, green, blue, alpha = image.split()
            if any(red.tobytes()) or any(green.tobytes()) or any(blue.tobytes()):
                raise ValueError(f"{path}: expected black RGB channels")
            alpha_bytes = alpha.tobytes()
    except (OSError, SyntaxError) as error:
        raise ValueError(f"{path}: invalid PNG: {error}") from error

    if set(alpha_bytes) - {0, 255}:
        raise ValueError(f"{path}: alpha must contain only 0 or 255")

    pixels = []
    source_width = SOURCE_SIZE[0]
    for y in range(0, SOURCE_SIZE[1], SCALE):
        for x in range(0, SOURCE_SIZE[0], SCALE):
            value = alpha_bytes[y * source_width + x]
            for dy in range(SCALE):
                row = (y + dy) * source_width + x
                if alpha_bytes[row:row + SCALE] != bytes([value]) * SCALE:
                    raise ValueError(f"{path}: nonuniform 8x8 block at {x},{y}")
            pixels.append(value == 255)
    return pixels


def convert(path):
    pixels = parse_source(path)
    data = bytes(
        sum(pixels[(page * 8 + bit) * WIDTH + x] << bit for bit in range(8))
        for page in range(HEIGHT // 8)
        for x in range(WIDTH)
    )
    if len(data) != 1024 or not any(data):
        raise ValueError(f"{path}: expected a nonblank 1024-byte bitmap")
    for y in range(HEIGHT):
        for x in range(WIDTH):
            packed = (data[(y // 8) * WIDTH + x] >> (y % 8)) & 1
            if packed != pixels[y * WIDTH + x]:
                raise ValueError(f"{path}: packing round-trip failed at {x},{y}")
    print(f"{path.name}: {sum(pixels)} lit pixels; {len(data)} bytes")
    return data


def header(name, data):
    symbol = name + "_bitmap"
    rows = ["    " + ", ".join(f"0x{value:02x}" for value in data[i:i + 16]) + ","
            for i in range(0, len(data), 16)]
    return (
        "#pragma once\n\n#include <stdint.h>\n\n"
        "#if defined(__AVR__)\n"
        "#include <avr/pgmspace.h>\n"
        "#elif !defined(PROGMEM)\n"
        "#define PROGMEM\n"
        "#endif\n\n"
        f"// Generated by tools/convert_assets.py from assets/{name}.PNG.\n"
        "// 128x64 alpha mask; white=1, page-column vertical LSB first.\n"
        "// Raw drawBitmap data: no dimension bytes. Include in one translation unit.\n"
        f"const uint8_t {symbol}[] PROGMEM = {{\n"
        + "\n".join(rows) + "\n};\n"
        + f'static_assert(sizeof({symbol}) == 1024, "Expected 128x64 bitmap");\n'
    )


def write_preview(path, data):
    pixels = bytes(
        255 if data[(y // 8) * WIDTH + x] & (1 << (y % 8)) else 0
        for y in range(HEIGHT)
        for x in range(WIDTH)
    )
    Image.frombytes("L", (WIDTH, HEIGHT), pixels).save(path)


# Базы для XOR-дельт кадров меню. Base хранится как обычный raw bitmap,
# остальные кадры группы — как дельты поверх неё.
BASE_MAIN = "mainmenu_sound"
BASE_SOUND = "soundmenu_off"

# (имя символа, исходный кадр, база)
DELTA_FRAMES = (
    ("play", "mainmenu_play", BASE_MAIN),
    ("about", "mainmenu_about", BASE_MAIN),
    ("main_exit", "mainmenu_exit", BASE_MAIN),
    ("soundmenu_on", "soundmenu_on", BASE_SOUND),
    ("soundmenu_exit", "soundmenu_exit", BASE_SOUND),
)


def encode_delta(base, target):
    """XOR-дельту: runs [off_lo, off_hi, len, payload...], завершение 0xFF 0xFF."""
    out = bytearray()
    i = 0
    n = len(base)
    while i < n:
        if base[i] == target[i]:
            i += 1
            continue
        start = i
        end = i
        while end < n and target[end] != base[end] and (end - start) < 255:
            end += 1
        payload = bytes(base[k] ^ target[k] for k in range(start, end))
        out += bytes([start & 0xFF, start >> 8, len(payload)])
        out += payload
        i = end
    out += b"\xff\xff"
    return bytes(out)


def decode_delta(base, delta):
    """Обратное преобразование: base XOR delta. Для round-trip проверки."""
    out = bytearray(base)
    p = 0
    while True:
        offset = delta[p] | (delta[p + 1] << 8)
        p += 2
        if offset == 0xFFFF:
            break
        length = delta[p]
        p += 1
        for k in range(length):
            out[offset + k] ^= delta[p + k]
        p += length
    return bytes(out)


def menu_frames_header(deltas):
    lines = [
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        "#if defined(__AVR__)",
        "#include <avr/pgmspace.h>",
        "#elif !defined(PROGMEM)",
        "#define PROGMEM",
        "#endif",
        "",
        "// Generated by tools/convert_assets.py from assets/*.PNG.",
        "// XOR deltas over the bases mainmenu_sound_bitmap and soundmenu_off_bitmap.",
        "// Format: runs [off_lo, off_hi, len, payload...], terminated by 0xFFFF.",
        "// No dimension metadata here.",
        "",
    ]
    for symbol, data in deltas:
        rows = ["    " + ", ".join(f"0x{value:02x}" for value in data[i:i + 16]) + ","
                for i in range(0, len(data), 16)]
        lines.append(f"const uint8_t menu_delta_{symbol}[] PROGMEM = {{")
        lines.extend(rows)
        lines.append("};")
        lines.append(f"static_assert(sizeof(menu_delta_{symbol}) >= 3 && "
                     f"sizeof(menu_delta_{symbol}) < 1024, "
                     '"Delta must stay below one raw frame");')
        lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="verify committed outputs without writing")
    parser.add_argument("--inspect", action="store_true",
                        help="report conversion statistics without writing")
    parser.add_argument("--preview-dir", type=Path,
                        help="write reconstructed 128x64 PNG previews")
    args = parser.parse_args()

    all_data = {}
    outputs = []
    for name in NAMES:
        data = convert(ROOT / "assets" / (name + ".PNG"))
        all_data[name] = data
        outputs.append((name, data, header(name, data)))
    print(f"Total raw flash payload: {sum(len(data) for _, data, _ in outputs)} bytes; "
          f"unique screens: {len({data for _, data, _ in outputs})}/{len(outputs)}")

    deltas = []
    for symbol, frame, base_name in DELTA_FRAMES:
        base = all_data[base_name]
        target = all_data[frame]
        delta = encode_delta(base, target)
        if decode_delta(base, delta) != target:
            raise ValueError(f"{frame}: delta round-trip failed")
        deltas.append((symbol, delta))
        print(f"{frame}: delta {len(delta)} bytes vs raw 1024")
    menu_text = menu_frames_header(deltas)
    delta_payload = sum(len(data) for _, data in deltas)
    menu_total = (len(all_data[BASE_MAIN]) + len(all_data[BASE_SOUND]) +
                  delta_payload)
    print(f"Menu frames (var bases + deltas): {menu_total} bytes "
          f"(bases {2 * 1024} + deltas {delta_payload}) "
          f"vs raw 8 screens {8 * 1024}")

    for name, data, text in outputs:
        destination = ROOT / "src" / "assets" / (name + ".h")
        if args.check:
            if not destination.exists() or destination.read_text(encoding="ascii") != text:
                raise ValueError(f"{destination}: missing or stale; rerun converter")
        elif not args.inspect:
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_text(text, encoding="ascii")
        if args.preview_dir:
            args.preview_dir.mkdir(parents=True, exist_ok=True)
            write_preview(args.preview_dir / (name + ".png"), data)

    destination = ROOT / "src" / "assets" / "menu_frames.h"
    if args.check:
        if not destination.exists() or destination.read_text(encoding="ascii") != menu_text:
            raise ValueError(f"{destination}: missing or stale; rerun converter")
    elif not args.inspect:
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(menu_text, encoding="ascii")

    if args.check:
        print("All generated headers match; raw frames, deltas, dimensions, alpha "
              "blocks and packing verified.")


if __name__ == "__main__":
    main()
